- README_CN.md
- cmd/kstone-api/app/server.go
- cmd/kstone-controller/main.go
please refer to the commit messages.
> some tiny fix and features for the first PR of kstone🤩

- .github/workflows/golangci-lint.yml
> add golangci-lint check

- pkg/clusterprovider/etcdcluster.go
- pkg/clusterprovider/plugins.go
- pkg/clusterprovider/providers/imported/cluster.go
- pkg/clusterprovider/providers/kstone/kstone.go
- pkg/controllers/etcdcluster/etcdclusters_controller.go
- pkg/inspection/healthy.go
1 fix typoc cheking
2 rename EtcdClusterProvider to Cluster
> fix: fix typos and rename EtcdClusterProvider to Cluster

- charts/README.md
- charts/README_CN.md
> docs: add minikube installation doc

- charts/charts/dashboard-api/values.yaml
- charts/charts/etcd-controller/values.yaml
- charts/charts/inspection-controller/values.yaml
> fix: add tag v0.0.1-alpha.2

- docs/installation/minikube-amd64.md
- docs/installation/minikube-macos.md
- docs/installation/tke.md
Better operations
- Set `prometheusOperator.enabled=false` in the file `charts/charts/kube-prometheus-stack/values.yaml`.
- Set `prometheus.enabled=false` in the file `charts/charts/kube-prometheus-stack/values.yaml`.
> update install docs of prometheus

- charts/charts/backup-operator/templates/deployment.yaml
update backup-operator startup args
> fix: update backup-operator startup args

- charts/charts/grafana/dashboards/0.json
> fix: make the inspection panel more beautiful

- charts/charts/dashboard-api/templates/deployment.yaml
- charts/charts/etcd-controller/templates/deployment.yaml
- charts/charts/inspection-controller/templates/deployment.yaml
- charts/values.yaml
1 add global.kstone.tag
2 support --set, kstone can be upgraded with the specific image tag
```
// install
helm install kstone . -n kstone --set global.kstone.tag=v0.0.1-alpha.2
// upgrade
helm upgrade kstone . -n kstone --set global.kstone.tag=v0.0.1-alpha.2
```
> build: add global.kstone.tag

- pkg/backup/backup.go
- pkg/clusterprovider/etcdcluster.go
- pkg/clusterprovider/helper.go
- pkg/clusterprovider/plugins.go
- pkg/clusterprovider/providers/imported/cluster.go
- pkg/clusterprovider/providers/kstone/kstone.go
- pkg/controllers/etcdcluster/etcdclusters_controller.go
- pkg/featureprovider/providers/backup/backup.go
- pkg/featureprovider/providers/consistency/consistency.go
- pkg/featureprovider/providers/healthy/healthy.go
- pkg/featureprovider/providers/monitor/monitor.go
- pkg/featureprovider/providers/request/request.go
- pkg/featureprovider/util/util.go
- pkg/inspection/consistency.go
- pkg/inspection/healthy.go
- pkg/inspection/inspection.go
- pkg/inspection/request.go
- pkg/monitor/prometheus.go
Some optimizations based on pr #44
> feat: support to disable feature

- charts/charts/grafana/dashboards/0.json
- pkg/apis/kstone/v1alpha1/types.go
- pkg/clusterprovider/helper.go
- pkg/etcd/helper.go
- pkg/featureprovider/providers/alarm/alarm.go
- pkg/featureprovider/providers/providers.go
- pkg/inspection/alarm.go
- pkg/inspection/metrics/metrics.go
- test/e2e/etcdcluster_test.go
- test/fixtures/fixtures.go
Step1: trigger etcd db no space alarm:
the alarm inspection:
Step2: disarm no space alarm
the alarm inspection (metrics cleared):
> feat: add etcd endpoint alarm inspection

- go.mod
- go.sum
- pkg/etcd/stats.go
- pkg/featureprovider/providers/consistency/consistency.go
- pkg/featureprovider/util/util.go
- pkg/inspection/consistency.go
- pkg/inspection/metrics/metrics.go
1. rename getEtcdNodeKeyDiff to getEtcdConsistencyDiff  
2. refactor  getEtcdConsistencyDiff  waitGroup to errgroup
3. add three consistency metrics , EtcdNodeRevisionDiff  EtcdNodeRaftAppliedIndexDiff   EtcdNodeRaftIndexDiff
> feat: add new metrics for consistency feature

- charts/charts/dashboard/values.yaml
- charts/values.test.yaml
- charts/values.yaml
> release v0.1.0-alpha.1

- pkg/apis/kstone/v1alpha1/types.go
- pkg/backup/plugins.go
- pkg/backup/providers/cos/cos.go
- pkg/featureprovider/providers/backup/backup.go
- pkg/featureprovider/providers/backupcheck/backupcheck.go
- pkg/featureprovider/providers/providers.go
- pkg/featureprovider/util/util.go
- pkg/inspection/backupcheck.go
- pkg/inspection/metrics/metrics.go
- test/e2e/etcdcluster_test.go
- test/fixtures/fixtures.go
This PR add two new metric: etcd_backup_files and etcd_failed_backup_files
one new inpsection task periodically collect aforementioned data.
> feat: add backup file check inspection

- pkg/featureprovider/util/util.go
- pkg/inspection/alarm.go
- pkg/inspection/backupcheck.go
- pkg/inspection/consistency.go
- pkg/inspection/healthy.go
- pkg/inspection/metrics/metrics.go
- pkg/inspection/request.go
add new counter metric for failed inspection
> feat: add new metric for failed inspection

- cmd/kstone-controller/etcdcluster-controller/controller.go
- cmd/kstone-controller/etcdinspection-controller/controller.go
- pkg/apis/kstone/v1alpha1/types.go
- pkg/backup/plugins.go
- pkg/backup/providers/cos/cos.go
- pkg/backup/storage.go
- pkg/controllers/etcdcluster/etcdclusters_controller.go
- pkg/controllers/etcdinspection/etcdinspection_controller.go
- pkg/etcd/tls.go
- pkg/featureprovider/feature.go
- pkg/featureprovider/plugins.go
- pkg/featureprovider/providers/alarm/alarm.go
- pkg/featureprovider/providers/backup/backup.go
- pkg/featureprovider/providers/backupcheck/backupcheck.go
- pkg/featureprovider/providers/consistency/consistency.go
- pkg/featureprovider/providers/healthy/healthy.go
- pkg/featureprovider/providers/providers.go
- pkg/featureprovider/providers/request/request.go
- pkg/featureprovider/util/util.go
- pkg/inspection/alarm.go
- pkg/inspection/backupcheck.go
- pkg/inspection/consistency.go
- pkg/inspection/healthy.go
- pkg/inspection/inspection.go
- pkg/inspection/metrics/metrics.go
- pkg/inspection/request.go
- pkg/router/router.go
- test/e2e/etcdcluster_test.go
- test/fixtures/fixtures.go
> cherry-pick pr #70, #71, #72, #73, #74 to release-0.1 branch

- charts/charts/grafana/dashboards/0.json
> feat: add db usage rate grafana panel

- charts/charts/grafana/dashboards/0.json
- before improve
<a href="https://ibb.co/YLCbLrm"><img src="https://i.ibb.co/gR26RnN/i-Shot2022-01-22-21-30-21.png" alt="i-Shot2022-01-22-21-30-21" border="0" /></a>
- after improve
<a href="https://ibb.co/C22YSK4"><img src="https://i.ibb.co/rsszX2q/i-Shot2022-01-22-21-31-52.png" alt="i-Shot2022-01-22-21-31-52" border="0" /></a>
> feat: add Hover tooltip decreasing sort 

- go.mod
- go.sum
- pkg/backup/providers/providers.go
- pkg/backup/providers/s3/clientwrapper.go
- pkg/backup/providers/s3/s3.go
add s3 support for inspect of backup check
> feat: add s3 backup and backup check

- docs/proposal/authentication-support/README.md
> docs: add authentication REST API example in proposal

- pkg/clusterprovider/etcdcluster.go
- pkg/clusterprovider/helper.go
- pkg/clusterprovider/providers/imported/cluster.go
- pkg/clusterprovider/providers/kstone/kstone.go
- pkg/controllers/etcdcluster/etcdclusters_controller.go
- pkg/controllers/etcdinspection/etcdinspection_controller.go
- pkg/etcd/client.go
- pkg/etcd/helper.go
- pkg/etcd/stats.go
- pkg/featureprovider/feature.go
- pkg/inspection/alarm.go
- pkg/inspection/consistency.go
- pkg/inspection/healthy.go
- pkg/inspection/inspection.go
- pkg/inspection/request.go
- pkg/router/router.go
- third_party/etcd-operator/pkg/apis/etcd/v1beta2/backup_types.go
- third_party/etcd-operator/pkg/backup/backup_manager.go
- third_party/etcd-operator/pkg/controller/backup-operator/abs_backup.go
- third_party/etcd-operator/pkg/controller/backup-operator/cos_backup.go
- third_party/etcd-operator/pkg/controller/backup-operator/gcs_backup.go
- third_party/etcd-operator/pkg/controller/backup-operator/oss_backup.go
- third_party/etcd-operator/pkg/controller/backup-operator/s3_backup.go
- third_party/etcd-operator/pkg/controller/backup-operator/sync.go
- third_party/etcd-operator/pkg/controller/backup-operator/util.go
/cc @tangcong @engow 
fix #100
> feat: support etcd cluster password authentication

- charts/charts/dashboard-api/templates/configmap.yaml
- charts/values.test.yaml
- cmd/kstone-api/app/server.go
- pkg/authentication/helper.go
- pkg/backup/backup.go
- pkg/backup/providers/cos/cos.go
- pkg/backup/providers/s3/s3.go
- pkg/backup/util.go
- pkg/controllers/etcdcluster/etcdclusters_controller.go
- pkg/etcd/client.go
- pkg/etcd/helper.go
- pkg/featureprovider/util/util.go
- pkg/inspection/backupcheck.go
- pkg/inspection/inspection.go
- pkg/router/router.go
> feat: support multiple ns

- charts/charts/grafana/dashboards/0.json
1. add lease metrics to troubleshoot [lease leak issue](https://github.com/etcd-io/etcd/pull/13206)
2. add  compaction metrics
> feature: add compaction,lease metrics

- third_party/etcd-operator/pkg/apis/etcd/v1beta2/backup_types.go
- third_party/etcd-operator/pkg/apis/etcd/v1beta2/restore_types.go
- third_party/etcd-operator/pkg/backup/reader/hostPath_reader.go
- third_party/etcd-operator/pkg/backup/writer/hostPath_writer.go
- third_party/etcd-operator/pkg/controller/backup-operator/hostPath_backup.go
- third_party/etcd-operator/pkg/controller/backup-operator/sync.go
- third_party/etcd-operator/pkg/controller/restore-operator/http.go
support backup etcd snapshop to local host dir
> add hostPath type for etcd backup
